language: python
python:
    - "3.6"

install:
  - pip install coveralls

before_script:
  - export APP_CONFIG=twootfeed/config.yml
  - cp twootfeed/config.example.yml twootfeed/config.yml

script:
  - python setup.py test

after_success:
  - coveralls
