language: python

matrix:
  include:
    - os: linux
      python: 3.6
    - dist: xenial
      python: 3.7
    - dist: xenial
      python: 3.8-dev

install:
  - pip install coveralls

before_script:
  - export TWOOTFEED_CONFIG_FILE=twootfeed/config.yml
  - cp twootfeed/config.example.yml twootfeed/config.yml

script:
  - python setup.py test

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]];
    then coveralls;
    fi
